from app.models.audit_event import AuditEvent
from app.models.admin import (
    AdminAuditEvent,
    AdminReviewDecision,
    AdminReviewTask,
    AdminRolePermission,
    AdminUser,
    AiConfidenceAlert,
    Assignment,
    CaseQueueItem,
    InternalNote,
)
from app.models.case import (
    CaseHistoryEvent,
    CaseOwner,
    CaseStatusHistory,
    CaseTag,
    LaboraCase,
)
from app.models.case_result import (
    CaseResult,
    EconomicEstimate,
    FinalViability,
    RecommendedRoute,
    ResultAuditEvent,
    ResultCard,
    ResultInconsistency,
)
from app.models.consent import (
    ConsentEvidence,
    ConsentIdempotencyKey,
    LegalDocument,
    UserConsent,
)
from app.models.delivery import (
    CaseClosure,
    DeliveryEvent,
    DeliveryPackage,
    DownloadFile,
    ShareLink,
)
from app.models.document import (
    Document,
    DocumentHash,
    DocumentPage,
    DocumentType,
    DocumentValidation,
    FileUpload,
)
from app.models.document_precheck import (
    AiConfidence,
    DocumentIssue,
    DocumentPrecheck,
    OcrJob,
    OcrPageResult,
)
from app.models.extraction import (
    ContributionGap,
    ContributionWeek,
    Employer,
    ExtractionAuditEvent,
    ExtractionConfirmation,
    ExtractionField,
    ExtractionIssue,
    ExtractionJob,
    ExtractionRun,
    LaborNovelty,
    LaborPeriod,
    SalaryBase,
    UserCorrection,
)
from app.models.external_auth_account import ExternalAuthAccount
from app.models.faq_item import FaqItem
from app.models.full_analysis import (
    AnalysisInconsistency,
    CalculationResult,
    ConfidenceScore,
    FullAnalysis,
    FullAnalysisJob,
    LegalRuleResult,
    Scenario,
)
from app.models.lead import Lead
from app.models.legal_action import (
    AiGenerationRun,
    DraftComment,
    DraftExport,
    DraftQualityCheck,
    DraftSection,
    DraftVersion,
    LegalAction,
    LegalActionJob,
    LegalDraft,
    LegalTemplate,
)
from app.models.oauth_state import OAuthState
from app.models.otp_code import OTPCode
from app.models.password_reset_token import PasswordResetToken
from app.models.paywall import ConversionEvent, LockedFeature, Paywall, PreviewResult
from app.models.payment import (
    Order,
    Payment,
    PaymentTransaction,
    Receipt,
    UnlockEvent,
)
from app.models.pension import (
    CaseEntitlement,
    DocumentExtraction,
    LegalRoute,
    LegalTemplateCatalogItem,
    PensionAffiliateProfile,
    PensionAlert,
    PensionLegalParameter,
    PensionMonthlyContribution,
    PensionSimulation,
    PensionSimulationAssumptions,
    PensionSimulationScenario,
)
from app.models.public_content import PublicContent
from app.models.public_event import PublicEvent
from app.models.professional_review import (
    LawyerComment,
    ProfessionalReview,
    ReviewedFile,
    ReviewerAssignment,
    ReviewOrder,
)
from app.models.pre_analysis import (
    CaseSignal,
    MissingDocument,
    PreAnalysis,
    PreAnalysisJob,
    PreIssue,
    PreViability,
)
from app.models.questionnaire import (
    AiQuestionnaireEvent,
    AnswerVersion,
    CaseProfile,
    CaseQuestionnaireSession,
    ConditionalRule,
    Question,
    QuestionnaireAnswer,
    QuestionnaireTemplate,
    QuestionOption,
)
from app.models.report import (
    ExportFile,
    Report,
    ReportGenerationJob,
    ReportSection,
    ReportTemplate,
    ReportVersion,
)
from app.models.session import Session
from app.models.user import User
from app.models.visitor_intent import VisitorIntent

__all__ = [
    "AuditEvent",
    "AdminAuditEvent",
    "AdminReviewDecision",
    "AdminReviewTask",
    "AdminRolePermission",
    "AdminUser",
    "AiQuestionnaireEvent",
    "AiConfidenceAlert",
    "AnswerVersion",
    "Assignment",
    "CaseHistoryEvent",
    "CaseOwner",
    "CaseClosure",
    "CaseQueueItem",
    "CaseEntitlement",
    "CaseResult",
    "CaseProfile",
    "CaseSignal",
    "CaseQuestionnaireSession",
    "CaseStatusHistory",
    "CaseTag",
    "ConditionalRule",
    "ConsentEvidence",
    "ConsentIdempotencyKey",
    "ContributionGap",
    "ContributionWeek",
    "ConversionEvent",
    "AiConfidence",
    "AnalysisInconsistency",
    "AiGenerationRun",
    "Document",
    "DocumentExtraction",
    "DeliveryEvent",
    "DeliveryPackage",
    "DocumentHash",
    "DocumentIssue",
    "DocumentPage",
    "DocumentPrecheck",
    "DraftComment",
    "DraftExport",
    "DraftQualityCheck",
    "DraftSection",
    "DraftVersion",
    "DownloadFile",
    "DocumentType",
    "DocumentValidation",
    "Employer",
    "ExtractionAuditEvent",
    "ExtractionConfirmation",
    "ExtractionField",
    "ExtractionIssue",
    "ExtractionJob",
    "ExtractionRun",
    "ExportFile",
    "ExternalAuthAccount",
    "FaqItem",
    "FileUpload",
    "EconomicEstimate",
    "FinalViability",
    "CalculationResult",
    "ConfidenceScore",
    "FullAnalysis",
    "FullAnalysisJob",
    "InternalNote",
    "Lead",
    "LegalAction",
    "LegalActionJob",
    "LegalDocument",
    "LegalDraft",
    "LegalRoute",
    "LegalRuleResult",
    "LegalTemplate",
    "LegalTemplateCatalogItem",
    "LaborNovelty",
    "LaborPeriod",
    "LaboraCase",
    "LawyerComment",
    "LockedFeature",
    "MissingDocument",
    "OAuthState",
    "OcrJob",
    "OcrPageResult",
    "OTPCode",
    "Order",
    "PasswordResetToken",
    "Paywall",
    "Payment",
    "PaymentTransaction",
    "PensionAffiliateProfile",
    "PensionAlert",
    "PensionLegalParameter",
    "PensionMonthlyContribution",
    "PensionSimulation",
    "PensionSimulationAssumptions",
    "PensionSimulationScenario",
    "PreAnalysis",
    "PreAnalysisJob",
    "PreIssue",
    "PreViability",
    "ProfessionalReview",
    "PreviewResult",
    "PublicContent",
    "PublicEvent",
    "Question",
    "QuestionnaireAnswer",
    "QuestionnaireTemplate",
    "QuestionOption",
    "Receipt",
    "RecommendedRoute",
    "Report",
    "ReportGenerationJob",
    "ReportSection",
    "ReportTemplate",
    "ReportVersion",
    "ResultAuditEvent",
    "ResultCard",
    "ResultInconsistency",
    "ReviewedFile",
    "ReviewerAssignment",
    "ReviewOrder",
    "SalaryBase",
    "Scenario",
    "Session",
    "ShareLink",
    "User",
    "UserConsent",
    "UserCorrection",
    "UnlockEvent",
    "VisitorIntent",
]
