LANDING_PUBLICA_CREATED = "landing_publica.created"
LANDING_PUBLICA_UPDATED = "landing_publica.updated"
LANDING_PUBLICA_VIEWED = "landing_publica.viewed"
LANDING_PUBLICA_SUBMITTED = "landing_publica.submitted"
LANDING_PUBLICA_APPROVED = "landing_publica.approved"
LANDING_PUBLICA_REJECTED = "landing_publica.rejected"
LANDING_PUBLICA_FAILED = "landing_publica.failed"
LANDING_PUBLICA_INTENT_CLASSIFIED = "landing_publica.intent_classified"
LANDING_PUBLICA_CHAT_STARTED = "landing_publica.chat_started"
LANDING_PUBLICA_CHAT_ESCALATED = "landing_publica.chat_escalated"
LANDING_PUBLICA_CTA_CLICKED = "landing_publica.cta_clicked"

ALLOWED_PUBLIC_EVENT_NAMES = {
    LANDING_PUBLICA_CREATED,
    LANDING_PUBLICA_UPDATED,
    LANDING_PUBLICA_VIEWED,
    LANDING_PUBLICA_SUBMITTED,
    LANDING_PUBLICA_APPROVED,
    LANDING_PUBLICA_REJECTED,
    LANDING_PUBLICA_FAILED,
    LANDING_PUBLICA_INTENT_CLASSIFIED,
    LANDING_PUBLICA_CHAT_STARTED,
    LANDING_PUBLICA_CHAT_ESCALATED,
    LANDING_PUBLICA_CTA_CLICKED,
}
